platform :ios, '10.0'

target 'SportsApp' do
  use_frameworks!

  pod 'Alamofire', '4.8.2'
  pod 'AlamofireImage', '3.5.0'
  pod 'youtube-ios-player-helper'
  pod 'ReachabilitySwift'
  pod 'FaveButton'

end
